import Ldsec

L1 = Ldsec.Ldsec()
L1.inserirInicio('Fim')
L1.inserirInicio('C')
L1.inserirInicio('A')
L1.inserirInicio('B')
L1.inserirInicio('C')
L1.inserirInicio('Inicio')
L1.inserirFim('Novo Fim')
L1.inserirInicio('Novo Inicio')
L1.inserirAposDet('C', 'H')
L1.imprimir()
L1.removerDet('Novo Fim')
L1.imprimir()
L1.removerInicio()
L1.removerFim()
L1.imprimir()
L1.imprimirReverso()
